### ISSUE TITLE
no more maintenance?

### ISSUE THREAD

**Issue by statusunknown418** [pr1mer-tech/Gravity#3]
I just came across your library and is something I've been looking for since I started learning SwiftUI and iOS development, but I saw that the last commit was around 2 years ago, do you have interest on continuing with it?

**Comment by arguiot** [comment]
Hey @statusunknown418 sorry for the super late response... I've pushed some updates with the V2, and I plan on maintaining it a bit more. You can check the docs: https://gravity.pr1mer.tech
